// Photo class to handle uploaded photos
// Holds original photo and a low-res proxy generated by the backend to speed up certain applications
export class Photo {
    constructor(hiResBlob) {
        this._originalURL = URL.createObjectURL(hiResBlob);
        this._proxyURL = null;
        this.isProcessing = true;
        this.done = this.createProxy(hiResBlob);
    }

    async createProxy(blob) {
        const bitmap = await createImageBitmap(blob);
        const canvas = document.createElement('canvas');
        const resolution = 512
        canvas.width = resolution;
        canvas.height = bitmap.height * (resolution / bitmap.width);
        const ctx = canvas.getContext('2d');
        ctx.drawImage(bitmap, 0, 0, canvas.width, canvas.height);

        const proxyBlob = await new Promise(res => canvas.toBlob(res, 'image/jpeg', 0.95));
        this._proxyURL = URL.createObjectURL(proxyBlob);
        this.isProcessing = false;
        bitmap.close();
    }
}
