// Photo class to handle uploaded photos
// Holds original photo and a low-res proxy generated by the backend to speed up certain applications
export class Photo {
    constructor(hiResBlob, lowResBlob) {
        this._originalURL = URL.createObjectURL(hiResBlob);
        this._proxyURL = URL.createObjectURL(lowResBlob);
    }
}
